### ISSUE TITLE
Installation from github

### ISSUE THREAD

**Issue by kevinVervier** [katiasmirn/PERFect#1]
Thanks for providing this useful tool. I would like to install it but got this error after running: devtools::install_github('katiasmirn/PERFect')

'Downloading GitHub repo katiasmirn/PERFect@master
Error in file(name, "wb") : cannot open the connection
In addition: Warning message:
In file(name, "wb") :
': Invalid argument'katiasmirn-PERFect-6382d37/Icon'

What is the best way to install the R package?

**Comment by kevinVervier** [comment]
I also tried to download the zip and install it with install.packages('C:/Users/kv4/Downloads/PERFect-master.zip', repos = NULL, type = "win.binary")

But same error.

**Comment by katiasmirn** [comment]
Dear Kevin,

I apologize for the problems with installation. We have updated the package
and it is now on the github. Please let me know if you still have any
problems.

**Comment by katiasmirn** [comment]
Also, you should install the package using the following commands in R

install.packages("devtools")
library(devtools)
install_github("katiasmirn/PERFect")
library(PERFect)
